### ISSUE TITLE
Prod deploy

### ISSUE THREAD

**Issue by ianks** [Zandrr/HackCU#31]
Hey @dawsonbotsford I don't think the new build is in production. When running the site, the newly sized images were not loading.

You need to build the site and have your server point to the `dist` folder for this to work.

## Steps

1. Pull down latest changes: `$ git checkout master && git pull`
1. Install the deps: `$ npm install && gulp`
1. Copy `dist` folder to server
1. Have server point to the `dist` folder

**Comment by ianks** [comment]
As a side note, this all could be automated, but I think we should move the whole site to a CDN anyway so I don't think it would be worth the effort.

**Comment by dawsonbotsford** [comment]
How do I get the "gulp" command to work? I am following you instructions on the live server. @ianks, do you want to just give ssh-keygen and I can add you in the server to do your thing?

**Comment by ianks** [comment]
to install gulp: `npm install -g grunt`, assuming you have Node.js installed.

**Comment by dawsonbotsford** [comment]
After performing ```npm install -g grunt```:

```$ npm install && gulp
No command 'gulp' found, did you mean:
 Command 'gslp' from package 'ghostscript' (main)
gulp: command not found```

**Comment by Zandrr** [comment]
Dawson, can you provide me with the SSH information.  I can take a whack at it!

**Comment by ianks** [comment]
it would be npm install -g gulp, not grunt

**Comment by ianks** [comment]
My b

**Comment by ianks** [comment]
By the way, I added setup instructions in the README.

**Comment by ianks** [comment]
PPS: https://api.github.com/users/ianks/keys

**Comment by dawsonbotsford** [comment]
Both added. Check your email for login info Ian. Campbell, check your facebook for your login info.
