### ISSUE TITLE
Use an SVG (or something Hi-Res) for the logo

### ISSUE THREAD

**Issue by ianks** [Zandrr/HackCU#32]
Currently the Logo looks highly pixelated, let's fix that. The logo should be able to be recreated pretty easily. I know @indiesquidge has been on his logo game recently, so I am politely requesting him to do so :smile: That is, of course, unless someone else wants to claim it.

**Comment by dawsonbotsford** [comment]
No @ianks, we have a dedicated designer who has created everything thus far. He is a pivotal member of the team. Care to chime in @alexwalling?

**Comment by ianks** [comment]
Ah sick, yeah didn't know that :dizzy_face:. @alexwalling any chance we can get and SVG of the image?

**Comment by dawsonbotsford** [comment]
No worries @ianks, he should be able to respond with some kind of time frame by tomorrow (he just got over being sick). Also check your email for a Drive invitation @ianks

**Comment by alexwalling** [comment]
Yeah, I'll get right on it! I've been working on homework tonight/dealing with being sick.  But I'll get you an SVG of it as soon as I can

**Comment by ianks** [comment]
Good stuff! Thanks @alexwalling

**Comment by alexwalling** [comment]
I've got the SVG, where do you want me to send it?

**Comment by alexwalling** [comment]
@ianks I've got the SVG, where do you want it?

**Comment by ianks** [comment]
Right here works!

**Comment by alexwalling** [comment]
I sent it to you in an email earlier today cause they attachment didn't support .svg  hope you got it
