### ISSUE TITLE
Server Access

### ISSUE THREAD

**Issue by dawsonbotsford** [Zandrr/HackCU#36]
Did @ianks and @Zandrr get server access working?

**Comment by ianks** [comment]
Yeah I did. I updated the site a couple of days ago.

**Comment by dawsonbotsford** [comment]
Beautiful, thanks for taking on so much! By the way, as a member of the planning committee you are disqualified to compete officially in HackCU by the MLH bylaws. But you can hack the whole time with me anyways :+1:

**Comment by ianks** [comment]
:+1:
