### ISSUE TITLE
Fuzzy headliner logo

### ISSUE THREAD

**Issue by dawsonbotsford** [Zandrr/HackCU#42]
The main logo does not look like the hd tif file @alexwalling showed me. @ianks, were you able to update the server?

**Comment by alexwalling** [comment]
It's the .svg that we want and it seems to just be linking to the .png still and the updates need to be pushed to the website host

**Comment by ianks** [comment]
No, the goal is to move from the server over to a CDN. The live preview is here: http://d1ma16vmjy33ld.cloudfront.net/

We need to make DNS point to this, then the server can be terminated.

**Comment by ianks** [comment]
Also, from a few metrics I did, we got about a 60% speed up boost by hosting on CDN. And the time to access this site will be constant throughout the world since there are caching servers all around the globe (SF, New York, China, etc.)

**Comment by ianks** [comment]
This will be resolved by #44
