### ISSUE TITLE
CDN Logo warping

### ISSUE THREAD

**Issue by dawsonbotsford** [Zandrr/HackCU#43]
![screenshot](http://i.imgur.com/305ZcIm.png)

**Comment by alexwalling** [comment]
And I'm getting this which isn't right either...
![screen shot 2015-03-02 at 11 19 37 am](https://cloud.githubusercontent.com/assets/9127455/6447253/112483ae-c0ce-11e4-84d4-706175b5a863.png)

**Comment by ianks** [comment]
I'm using Firefox on Mac and it looks decent. I think the fonts that might have been used are not cross-browser compatible. I think the logical step would be to render a high-quality PNG from this, as we cannot ensure the fonts will be rendered properly.

**Comment by ianks** [comment]
This will be solved by #44
