### ISSUE TITLE
render a high-quality PNG

### ISSUE THREAD

**Issue by dawsonbotsford** [Zandrr/HackCU#44]
To fix the CDN Warping

**Comment by ianks** [comment]
This should  be done in the build step. That way we can keep the SVG and automate this workflow,

**Comment by ianks** [comment]
Actually, I take that back. Let's just render it once and for all.

**Comment by alexwalling** [comment]
Here's the .svg rendered as a .png.  It should be a good size and work well hopefully. the _screen is a little bit smaller of a file. So whichever one works better. 
![logo_medium](https://cloud.githubusercontent.com/assets/9127455/6456672/3d727240-c12d-11e4-8c65-6f19ff20df7f.png)
![logo_screen](https://cloud.githubusercontent.com/assets/9127455/6456674/4ab3dba6-c12d-11e4-8d41-26cb11aa46dd.png)

**Comment by ianks** [comment]
Thanks so much @alexwalling ! :yellow_heart:
